# Generated by Django 3.2.15 on 2023-05-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_name', models.CharField(max_length=10, verbose_name='床号')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('people_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('check_in_time', models.DateTimeField(verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(verbose_name='退房时间')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='押金')),
                ('remark', models.CharField(max_length=11, verbose_name='备注')),
                ('bed_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.bednumber', verbose_name='床号')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.department', verbose_name='关联部门表')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='租金单价')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=10, verbose_name='楼名')),
                ('floor', models.CharField(max_length=10, verbose_name='楼层')),
                ('room_number', models.CharField(max_length=10, verbose_name='房间号')),
                ('number_of_people', models.SmallIntegerField(verbose_name='入住人数')),
                ('standard_number_of_people', models.SmallIntegerField(verbose_name='配标人数')),
                ('empty_bed_number', models.SmallIntegerField(verbose_name='空床数')),
                ('room_personnel', models.CharField(max_length=50, verbose_name='房间人员')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='房屋类型')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('power', models.SmallIntegerField(verbose_name='权限')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='WaterElectricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_water_code', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='水费表码起')),
                ('end_water_code', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='水费表码止')),
                ('water_sum', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='水表数')),
                ('water_price', models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='水费单价')),
                ('water_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='水费金额')),
                ('water_time', models.DateTimeField(verbose_name='水费抄表时间')),
                ('start_electricity_code', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='电表表码起')),
                ('end_electricity_code', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='电表表码止')),
                ('electricity_sum', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='电表数')),
                ('electricity_price', models.DecimalField(decimal_places=2, default=1.2, max_digits=20, verbose_name='电费单价')),
                ('electricity_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='电费金额')),
                ('electricity_time', models.DateTimeField(verbose_name='电费抄表时间')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.room', verbose_name='房间编码')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.roomtype', verbose_name='房屋类型'),
        ),
        migrations.CreateModel(
            name='RentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='应缴金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='实缴金额')),
                ('payment_date', models.DateTimeField(verbose_name='缴费时间')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.user')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.people')),
                ('rent_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.rent')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.user', verbose_name='录入人'),
        ),
    ]
