# Generated by Django 3.2.15 on 2023-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='余额'),
        ),
    ]
