# Generated by Django 3.2.15 on 2023-05-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
    ]
