# Generated by Django 3.2.15 on 2023-06-08 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_rentdetails_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='deduction_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='扣款时间'),
            preserve_default=False,
        ),
    ]
