# Generated by Django 3.2.15 on 2023-05-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_rentdetails_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=20, null=True, verbose_name='设备名称')),
                ('device_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='设备价格')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Category_name', models.CharField(max_length=20, null=True, verbose_name='房屋类别')),
            ],
        ),
        migrations.CreateModel(
            name='RepairReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_time', models.DateTimeField(verbose_name='报修日期')),
                ('fault_description', models.CharField(max_length=50, null=True, verbose_name='故障说明')),
                ('is_quality_guarantee_period', models.BooleanField(null=True, verbose_name='是否保质期内')),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='维修费用')),
                ('is_self_cost', models.BooleanField(null=True, verbose_name='是否自费')),
                ('repair_people', models.CharField(max_length=10, null=True, verbose_name='维修人')),
                ('is_repaired', models.BooleanField(default=False, verbose_name='是否修好')),
                ('repair_date', models.DateField(verbose_name='修复日期')),
                ('repair_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.devicelist')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='device_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.devicelist'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.roomcategory'),
        ),
    ]
