# Generated by Django 3.2.15 on 2023-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_auto_20230523_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_used',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
