# Generated by Django 3.2.15 on 2023-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_rentdetails_deduction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
