# Generated by Django 3.2.15 on 2023-06-01 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_auto_20230530_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_name', to='dorm.room', verbose_name='房间号'),
        ),
    ]
