# Generated by Django 3.2.15 on 2023-06-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_rentdetails_modified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='rent_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.rent', verbose_name='租金单价'),
        ),
    ]
