# Generated by Django 3.2.15 on 2023-05-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_room_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_personnel',
        ),
        migrations.AddField(
            model_name='people',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.room'),
        ),
    ]
