# Generated by Django 3.2.15 on 2023-05-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0005_auto_20230523_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='remark',
            field=models.CharField(max_length=11, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='room',
            name='device_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.devicelist', verbose_name='设备清单'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.roomcategory', verbose_name='房屋类别'),
        ),
    ]
