# Generated by Django 3.2.15 on 2023-06-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0005_people_rent_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdetails',
            name='rent_price',
        ),
    ]
