# Generated by Django 3.2.15 on 2023-06-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0006_alter_people_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别'),
        ),
    ]
