# Generated by Django 3.2.15 on 2023-05-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0006_auto_20230523_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='check_out_time',
            field=models.DateTimeField(null=True, verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='people',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.room', verbose_name='房间号'),
        ),
    ]
