# Generated by Django 3.2.15 on 2023-06-08 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0006_remove_rentdetails_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(1, '已缴费'), (2, '未缴费')], default=0, verbose_name='交费状态'),
            preserve_default=False,
        ),
    ]
