# Generated by Django 3.2.15 on 2023-06-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0007_alter_people_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='check_out_time',
            field=models.DateField(blank=True, null=True, verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='people',
            name='remark',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='备注'),
        ),
    ]
