# Generated by Django 3.2.15 on 2023-05-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0008_auto_20230526_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='check_in_time',
            field=models.DateField(verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='people',
            name='check_out_time',
            field=models.DateField(null=True, verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='people',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_name', to='dorm.room', verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.roomcategory', verbose_name='房屋类别'),
        ),
    ]
