# Generated by Django 3.2.15 on 2023-06-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0008_auto_20230605_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterelectricity',
            name='electricity_sum',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='电表数'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='end_electricity_code',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='电表表码止'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='end_water_code',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='水费表码止'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='start_electricity_code',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='电表表码起'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='start_water_code',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='水费表码起'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='water_price',
            field=models.DecimalField(decimal_places=2, default=4.81, max_digits=20, verbose_name='水费单价'),
        ),
    ]
