# Generated by Django 3.2.15 on 2023-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0008_alter_rentdetails_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='余额'),
        ),
    ]
