# Generated by Django 3.2.15 on 2023-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0009_alter_rentdetails_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(1, '已缴费'), (0, '未缴费')], default=0, verbose_name='交费状态'),
        ),
    ]
