# Generated by Django 3.2.15 on 2023-05-27 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0009_auto_20230527_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
