# Generated by Django 3.2.15 on 2023-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0009_auto_20230605_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterelectricity',
            name='sum_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总金额'),
        ),
    ]
