# Generated by Django 3.2.15 on 2023-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0011_devicedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='device_number',
            field=models.IntegerField(default=1, verbose_name='设备数量'),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='remark',
            field=models.CharField(max_length=50, null=True, verbose_name='备注'),
        ),
    ]
