# Generated by Django 3.2.15 on 2023-06-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0012_auto_20230610_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdetails',
            name='balance',
        ),
    ]
