# Generated by Django 3.2.15 on 2023-05-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0012_auto_20230527_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterelectricity',
            name='mouth',
            field=models.CharField(default='202305', max_length=6, verbose_name='年月数'),
        ),
    ]
