# Generated by Django 3.2.15 on 2023-05-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0013_waterelectricity_mouth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterelectricity',
            name='mouth',
            field=models.CharField(max_length=6, verbose_name='年月数'),
        ),
    ]
