# Generated by Django 3.2.15 on 2023-06-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0013_remove_rentdetails_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorm.room', verbose_name='房间号'),
            preserve_default=False,
        ),
    ]
