# Generated by Django 3.2.15 on 2023-06-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0015_alter_people_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWaterElectricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='实缴金额')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='缴费时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.user', verbose_name='创建人')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.room', verbose_name='房间号')),
            ],
            options={
                'verbose_name': '付款水电费记录表',
                'verbose_name_plural': '付款水电费记录表',
            },
        ),
    ]
