# Generated by Django 3.2.15 on 2023-06-17 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0017_room_waterelectricity_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterelectricity',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name='扣款金额'),
        ),
        migrations.AddField(
            model_name='waterelectricity',
            name='deduction_reason',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='扣款原因'),
        ),
        migrations.AddField(
            model_name='waterelectricity',
            name='deduction_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='扣款时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterelectricity',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='waterelectricity',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(1, '已缴费'), (0, '未缴费')], default=0, verbose_name='交费状态'),
        ),
        migrations.AddField(
            model_name='waterelectricity',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='rentdetails',
            name='year_month',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='年月数'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='sum_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='应付总金额'),
        ),
    ]
