# Generated by Django 3.2.15 on 2023-06-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0018_auto_20230617_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterelectricity',
            name='electricity_payment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.user', verbose_name='扣费人'),
        ),
    ]
