# Generated by Django 3.2.15 on 2023-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0019_waterelectricity_electricity_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairreport',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='维修费用'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='repair_date',
            field=models.DateField(blank=True, null=True, verbose_name='修复日期'),
        ),
    ]
