# Generated by Django 3.2.15 on 2023-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0021_alter_repairreport_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairreport',
            name='people',
        ),
        migrations.RemoveField(
            model_name='repairreport',
            name='room',
        ),
    ]
