# Generated by Django 3.2.15 on 2023-06-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0022_auto_20230618_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairreport',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.people', verbose_name='报修人'),
        ),
        migrations.AddField(
            model_name='repairreport',
            name='room',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='dorm.room', verbose_name='房间号'),
            preserve_default=False,
        ),
    ]
