# Generated by Django 3.2.15 on 2023-06-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0025_alter_repairreport_repair_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='payment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_user', to='dorm.user', verbose_name='扣费人'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='repair_people',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='维修人'),
        ),
    ]
