# Generated by Django 3.2.15 on 2023-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0026_auto_20230619_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='扣款金额'),
        ),
        migrations.AlterField(
            model_name='rentdetails',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='应缴金额'),
        ),
    ]
