# Generated by Django 3.2.15 on 2023-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0029_auto_20230707_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='room_record',
            field=models.ManyToManyField(related_name='room_record', to='dorm.Room', verbose_name='入住记录'),
        ),
    ]
