# Generated by Django 3.2.15 on 2023-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0030_people_room_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='check_in_stats',
            field=models.BooleanField(choices=[(1, '入住中'), (0, '已退房')], default=1, verbose_name='入住状态'),
        ),
    ]
