# Generated by Django 3.2.15 on 2023-07-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0031_people_check_in_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='room_record',
        ),
    ]
