# Generated by Django 3.2.15 on 2023-07-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0033_checkinrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='create_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='dorm.user', verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
