# Generated by Django 3.2.15 on 2023-08-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0034_checkinrecord_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterelectricity',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='扣款金额'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='deduction_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='扣款时间'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='electricity_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='电费单价'),
        ),
        migrations.AlterField(
            model_name='waterelectricity',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
