# Generated by Django 3.2.15 on 2023-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0035_auto_20230810_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterelectricity',
            name='water_sum',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='水表数'),
        ),
    ]
