# Generated by Django 3.2.15 on 2023-09-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0036_alter_waterelectricity_water_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='余额'),
        ),
    ]
